version: '2'

networks:
  app-tier:
    driver: bridge

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=transactions
      - MARIADB_DATABASE=transactions
      - MARIADB_PASSWORD=transactions
    networks:
      - app-tier

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
#    volumes:
#      - ./:/bitnami/redis/data
    networks:
      - app-tier

  transactions-test:
    tty: true
    image: bitnami/laravel:6-debian-9
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=transactions
      - DB_DATABASE=transactions
      - DB_PASSWORD=transactions
      - COMPOSE_PROJECT_NAME=transactions-test
    networks:
      - app-tier
    depends_on:
      - mariadb
      - redis
    links:
      - "mariadb:database"
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    privileged: true # Privileged mode could be required to run this container under Windows
